# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to=b'uploads'),
        ),
    ]
