# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170408_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to=b'static/imgs/events'),
        ),
    ]
