# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-05 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat1', models.IntegerField()),
                ('stat2', models.IntegerField()),
                ('stat3', models.IntegerField()),
                ('stat4', models.IntegerField()),
                ('stat5', models.IntegerField()),
                ('stat6', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='people')),
                ('image2', models.ImageField(upload_to='people')),
            ],
        ),
    ]
